// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: flash_calibration.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlashCalibration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LedcoolLux       *float32 `protobuf:"fixed32,1,req,name=ledcool_lux,json=ledcoolLux" json:"ledcool_lux,omitempty"`
	LedcoolMaxLumens *float32 `protobuf:"fixed32,2,req,name=ledcool_max_lumens,json=ledcoolMaxLumens" json:"ledcool_max_lumens,omitempty"`
	LedcoolCct       *float32 `protobuf:"fixed32,3,req,name=ledcool_cct,json=ledcoolCct" json:"ledcool_cct,omitempty"`
	LedwarmLux       *float32 `protobuf:"fixed32,4,req,name=ledwarm_lux,json=ledwarmLux" json:"ledwarm_lux,omitempty"`
	LedwarmMaxLumens *float32 `protobuf:"fixed32,5,req,name=ledwarm_max_lumens,json=ledwarmMaxLumens" json:"ledwarm_max_lumens,omitempty"`
	LedwarmCct       *float32 `protobuf:"fixed32,6,req,name=ledwarm_cct,json=ledwarmCct" json:"ledwarm_cct,omitempty"`
}

func (x *FlashCalibration) Reset() {
	*x = FlashCalibration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flash_calibration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlashCalibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashCalibration) ProtoMessage() {}

func (x *FlashCalibration) ProtoReflect() protoreflect.Message {
	mi := &file_flash_calibration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashCalibration.ProtoReflect.Descriptor instead.
func (*FlashCalibration) Descriptor() ([]byte, []int) {
	return file_flash_calibration_proto_rawDescGZIP(), []int{0}
}

func (x *FlashCalibration) GetLedcoolLux() float32 {
	if x != nil && x.LedcoolLux != nil {
		return *x.LedcoolLux
	}
	return 0
}

func (x *FlashCalibration) GetLedcoolMaxLumens() float32 {
	if x != nil && x.LedcoolMaxLumens != nil {
		return *x.LedcoolMaxLumens
	}
	return 0
}

func (x *FlashCalibration) GetLedcoolCct() float32 {
	if x != nil && x.LedcoolCct != nil {
		return *x.LedcoolCct
	}
	return 0
}

func (x *FlashCalibration) GetLedwarmLux() float32 {
	if x != nil && x.LedwarmLux != nil {
		return *x.LedwarmLux
	}
	return 0
}

func (x *FlashCalibration) GetLedwarmMaxLumens() float32 {
	if x != nil && x.LedwarmMaxLumens != nil {
		return *x.LedwarmMaxLumens
	}
	return 0
}

func (x *FlashCalibration) GetLedwarmCct() float32 {
	if x != nil && x.LedwarmCct != nil {
		return *x.LedwarmCct
	}
	return 0
}

var File_flash_calibration_proto protoreflect.FileDescriptor

var file_flash_calibration_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x6c, 0x61, 0x73, 0x68, 0x5f, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x74, 0x70, 0x62, 0x22,
	0xf2, 0x01, 0x0a, 0x10, 0x46, 0x6c, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c, 0x5f,
	0x6c, 0x75, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0a, 0x6c, 0x65, 0x64, 0x63, 0x6f,
	0x6f, 0x6c, 0x4c, 0x75, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c,
	0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x75, 0x6d, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x10, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c, 0x4d, 0x61, 0x78, 0x4c, 0x75, 0x6d,
	0x65, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c, 0x5f, 0x63,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0a, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6f,
	0x6c, 0x43, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x64, 0x77, 0x61, 0x72, 0x6d, 0x5f,
	0x6c, 0x75, 0x78, 0x18, 0x04, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0a, 0x6c, 0x65, 0x64, 0x77, 0x61,
	0x72, 0x6d, 0x4c, 0x75, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x65, 0x64, 0x77, 0x61, 0x72, 0x6d,
	0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x75, 0x6d, 0x65, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x10, 0x6c, 0x65, 0x64, 0x77, 0x61, 0x72, 0x6d, 0x4d, 0x61, 0x78, 0x4c, 0x75, 0x6d,
	0x65, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x64, 0x77, 0x61, 0x72, 0x6d, 0x5f, 0x63,
	0x63, 0x74, 0x18, 0x06, 0x20, 0x02, 0x28, 0x02, 0x52, 0x0a, 0x6c, 0x65, 0x64, 0x77, 0x61, 0x72,
	0x6d, 0x43, 0x63, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x74, 0x70, 0x62, 0x3b, 0x6c,
	0x74, 0x70, 0x62,
}

var (
	file_flash_calibration_proto_rawDescOnce sync.Once
	file_flash_calibration_proto_rawDescData = file_flash_calibration_proto_rawDesc
)

func file_flash_calibration_proto_rawDescGZIP() []byte {
	file_flash_calibration_proto_rawDescOnce.Do(func() {
		file_flash_calibration_proto_rawDescData = protoimpl.X.CompressGZIP(file_flash_calibration_proto_rawDescData)
	})
	return file_flash_calibration_proto_rawDescData
}

var file_flash_calibration_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flash_calibration_proto_goTypes = []any{
	(*FlashCalibration)(nil), // 0: ltpb.FlashCalibration
}
var file_flash_calibration_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flash_calibration_proto_init() }
func file_flash_calibration_proto_init() {
	if File_flash_calibration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flash_calibration_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FlashCalibration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flash_calibration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flash_calibration_proto_goTypes,
		DependencyIndexes: file_flash_calibration_proto_depIdxs,
		MessageInfos:      file_flash_calibration_proto_msgTypes,
	}.Build()
	File_flash_calibration_proto = out.File
	file_flash_calibration_proto_rawDesc = nil
	file_flash_calibration_proto_goTypes = nil
	file_flash_calibration_proto_depIdxs = nil
}
