// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: matrix4x4f.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Matrix4X4F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X00 *float32 `protobuf:"fixed32,1,req,name=x00" json:"x00,omitempty"`
	X01 *float32 `protobuf:"fixed32,2,req,name=x01" json:"x01,omitempty"`
	X02 *float32 `protobuf:"fixed32,3,req,name=x02" json:"x02,omitempty"`
	X03 *float32 `protobuf:"fixed32,4,req,name=x03" json:"x03,omitempty"`
	X10 *float32 `protobuf:"fixed32,5,req,name=x10" json:"x10,omitempty"`
	X11 *float32 `protobuf:"fixed32,6,req,name=x11" json:"x11,omitempty"`
	X12 *float32 `protobuf:"fixed32,7,req,name=x12" json:"x12,omitempty"`
	X13 *float32 `protobuf:"fixed32,8,req,name=x13" json:"x13,omitempty"`
	X20 *float32 `protobuf:"fixed32,9,req,name=x20" json:"x20,omitempty"`
	X21 *float32 `protobuf:"fixed32,10,req,name=x21" json:"x21,omitempty"`
	X22 *float32 `protobuf:"fixed32,11,req,name=x22" json:"x22,omitempty"`
	X23 *float32 `protobuf:"fixed32,12,req,name=x23" json:"x23,omitempty"`
	X30 *float32 `protobuf:"fixed32,13,req,name=x30" json:"x30,omitempty"`
	X31 *float32 `protobuf:"fixed32,14,req,name=x31" json:"x31,omitempty"`
	X32 *float32 `protobuf:"fixed32,15,req,name=x32" json:"x32,omitempty"`
	X33 *float32 `protobuf:"fixed32,16,req,name=x33" json:"x33,omitempty"`
}

func (x *Matrix4X4F) Reset() {
	*x = Matrix4X4F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matrix4x4f_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matrix4X4F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X4F) ProtoMessage() {}

func (x *Matrix4X4F) ProtoReflect() protoreflect.Message {
	mi := &file_matrix4x4f_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X4F.ProtoReflect.Descriptor instead.
func (*Matrix4X4F) Descriptor() ([]byte, []int) {
	return file_matrix4x4f_proto_rawDescGZIP(), []int{0}
}

func (x *Matrix4X4F) GetX00() float32 {
	if x != nil && x.X00 != nil {
		return *x.X00
	}
	return 0
}

func (x *Matrix4X4F) GetX01() float32 {
	if x != nil && x.X01 != nil {
		return *x.X01
	}
	return 0
}

func (x *Matrix4X4F) GetX02() float32 {
	if x != nil && x.X02 != nil {
		return *x.X02
	}
	return 0
}

func (x *Matrix4X4F) GetX03() float32 {
	if x != nil && x.X03 != nil {
		return *x.X03
	}
	return 0
}

func (x *Matrix4X4F) GetX10() float32 {
	if x != nil && x.X10 != nil {
		return *x.X10
	}
	return 0
}

func (x *Matrix4X4F) GetX11() float32 {
	if x != nil && x.X11 != nil {
		return *x.X11
	}
	return 0
}

func (x *Matrix4X4F) GetX12() float32 {
	if x != nil && x.X12 != nil {
		return *x.X12
	}
	return 0
}

func (x *Matrix4X4F) GetX13() float32 {
	if x != nil && x.X13 != nil {
		return *x.X13
	}
	return 0
}

func (x *Matrix4X4F) GetX20() float32 {
	if x != nil && x.X20 != nil {
		return *x.X20
	}
	return 0
}

func (x *Matrix4X4F) GetX21() float32 {
	if x != nil && x.X21 != nil {
		return *x.X21
	}
	return 0
}

func (x *Matrix4X4F) GetX22() float32 {
	if x != nil && x.X22 != nil {
		return *x.X22
	}
	return 0
}

func (x *Matrix4X4F) GetX23() float32 {
	if x != nil && x.X23 != nil {
		return *x.X23
	}
	return 0
}

func (x *Matrix4X4F) GetX30() float32 {
	if x != nil && x.X30 != nil {
		return *x.X30
	}
	return 0
}

func (x *Matrix4X4F) GetX31() float32 {
	if x != nil && x.X31 != nil {
		return *x.X31
	}
	return 0
}

func (x *Matrix4X4F) GetX32() float32 {
	if x != nil && x.X32 != nil {
		return *x.X32
	}
	return 0
}

func (x *Matrix4X4F) GetX33() float32 {
	if x != nil && x.X33 != nil {
		return *x.X33
	}
	return 0
}

var File_matrix4x4f_proto protoreflect.FileDescriptor

var file_matrix4x4f_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x34, 0x78, 0x34, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6c, 0x74, 0x70, 0x62, 0x22, 0xac, 0x02, 0x0a, 0x0a, 0x4d, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x34, 0x78, 0x34, 0x46, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x30, 0x30, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x30, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x30, 0x31,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x30, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x78,
	0x30, 0x32, 0x18, 0x03, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x30, 0x32, 0x12, 0x10, 0x0a,
	0x03, 0x78, 0x30, 0x33, 0x18, 0x04, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x30, 0x33, 0x12,
	0x10, 0x0a, 0x03, 0x78, 0x31, 0x30, 0x18, 0x05, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x31,
	0x30, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x31, 0x31, 0x18, 0x06, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03,
	0x78, 0x31, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x31, 0x32, 0x18, 0x07, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x03, 0x78, 0x31, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x31, 0x33, 0x18, 0x08, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x03, 0x78, 0x31, 0x33, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x32, 0x30, 0x18, 0x09,
	0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x32, 0x30, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x32, 0x31,
	0x18, 0x0a, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x32, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x78,
	0x32, 0x32, 0x18, 0x0b, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x32, 0x32, 0x12, 0x10, 0x0a,
	0x03, 0x78, 0x32, 0x33, 0x18, 0x0c, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x32, 0x33, 0x12,
	0x10, 0x0a, 0x03, 0x78, 0x33, 0x30, 0x18, 0x0d, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03, 0x78, 0x33,
	0x30, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x33, 0x31, 0x18, 0x0e, 0x20, 0x02, 0x28, 0x02, 0x52, 0x03,
	0x78, 0x33, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x33, 0x32, 0x18, 0x0f, 0x20, 0x02, 0x28, 0x02,
	0x52, 0x03, 0x78, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x33, 0x33, 0x18, 0x10, 0x20, 0x02,
	0x28, 0x02, 0x52, 0x03, 0x78, 0x33, 0x33, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x74, 0x70,
	0x62, 0x3b, 0x6c, 0x74, 0x70, 0x62,
}

var (
	file_matrix4x4f_proto_rawDescOnce sync.Once
	file_matrix4x4f_proto_rawDescData = file_matrix4x4f_proto_rawDesc
)

func file_matrix4x4f_proto_rawDescGZIP() []byte {
	file_matrix4x4f_proto_rawDescOnce.Do(func() {
		file_matrix4x4f_proto_rawDescData = protoimpl.X.CompressGZIP(file_matrix4x4f_proto_rawDescData)
	})
	return file_matrix4x4f_proto_rawDescData
}

var file_matrix4x4f_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_matrix4x4f_proto_goTypes = []any{
	(*Matrix4X4F)(nil), // 0: ltpb.Matrix4x4F
}
var file_matrix4x4f_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matrix4x4f_proto_init() }
func file_matrix4x4f_proto_init() {
	if File_matrix4x4f_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matrix4x4f_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Matrix4X4F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matrix4x4f_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_matrix4x4f_proto_goTypes,
		DependencyIndexes: file_matrix4x4f_proto_depIdxs,
		MessageInfos:      file_matrix4x4f_proto_msgTypes,
	}.Build()
	File_matrix4x4f_proto = out.File
	file_matrix4x4f_proto_rawDesc = nil
	file_matrix4x4f_proto_goTypes = nil
	file_matrix4x4f_proto_depIdxs = nil
}
