// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: point2i.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point2I struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
}

func (x *Point2I) Reset() {
	*x = Point2I{}
	if protoimpl.UnsafeEnabled {
		mi := &file_point2i_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point2I) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2I) ProtoMessage() {}

func (x *Point2I) ProtoReflect() protoreflect.Message {
	mi := &file_point2i_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point2I.ProtoReflect.Descriptor instead.
func (*Point2I) Descriptor() ([]byte, []int) {
	return file_point2i_proto_rawDescGZIP(), []int{0}
}

func (x *Point2I) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Point2I) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

var File_point2i_proto protoreflect.FileDescriptor

var file_point2i_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6c, 0x74, 0x70, 0x62, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0x49,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x79, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x2f, 0x6c, 0x74, 0x70, 0x62, 0x3b, 0x6c, 0x74, 0x70, 0x62,
}

var (
	file_point2i_proto_rawDescOnce sync.Once
	file_point2i_proto_rawDescData = file_point2i_proto_rawDesc
)

func file_point2i_proto_rawDescGZIP() []byte {
	file_point2i_proto_rawDescOnce.Do(func() {
		file_point2i_proto_rawDescData = protoimpl.X.CompressGZIP(file_point2i_proto_rawDescData)
	})
	return file_point2i_proto_rawDescData
}

var file_point2i_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_point2i_proto_goTypes = []any{
	(*Point2I)(nil), // 0: ltpb.Point2I
}
var file_point2i_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_point2i_proto_init() }
func file_point2i_proto_init() {
	if File_point2i_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_point2i_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Point2I); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_point2i_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_point2i_proto_goTypes,
		DependencyIndexes: file_point2i_proto_depIdxs,
		MessageInfos:      file_point2i_proto_msgTypes,
	}.Build()
	File_point2i_proto = out.File
	file_point2i_proto_rawDesc = nil
	file_point2i_proto_goTypes = nil
	file_point2i_proto_depIdxs = nil
}
