// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: range2f.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Range2F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinVal *float32 `protobuf:"fixed32,1,req,name=min_val,json=minVal" json:"min_val,omitempty"`
	MaxVal *float32 `protobuf:"fixed32,2,req,name=max_val,json=maxVal" json:"max_val,omitempty"`
}

func (x *Range2F) Reset() {
	*x = Range2F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_range2f_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range2F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range2F) ProtoMessage() {}

func (x *Range2F) ProtoReflect() protoreflect.Message {
	mi := &file_range2f_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range2F.ProtoReflect.Descriptor instead.
func (*Range2F) Descriptor() ([]byte, []int) {
	return file_range2f_proto_rawDescGZIP(), []int{0}
}

func (x *Range2F) GetMinVal() float32 {
	if x != nil && x.MinVal != nil {
		return *x.MinVal
	}
	return 0
}

func (x *Range2F) GetMaxVal() float32 {
	if x != nil && x.MaxVal != nil {
		return *x.MaxVal
	}
	return 0
}

var File_range2f_proto protoreflect.FileDescriptor

var file_range2f_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x32, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6c, 0x74, 0x70, 0x62, 0x22, 0x3b, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x32, 0x46,
	0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x02, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78,
	0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x02, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x56,
	0x61, 0x6c, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x74, 0x70, 0x62, 0x3b, 0x6c, 0x74, 0x70,
	0x62,
}

var (
	file_range2f_proto_rawDescOnce sync.Once
	file_range2f_proto_rawDescData = file_range2f_proto_rawDesc
)

func file_range2f_proto_rawDescGZIP() []byte {
	file_range2f_proto_rawDescOnce.Do(func() {
		file_range2f_proto_rawDescData = protoimpl.X.CompressGZIP(file_range2f_proto_rawDescData)
	})
	return file_range2f_proto_rawDescData
}

var file_range2f_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_range2f_proto_goTypes = []any{
	(*Range2F)(nil), // 0: ltpb.Range2F
}
var file_range2f_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_range2f_proto_init() }
func file_range2f_proto_init() {
	if File_range2f_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_range2f_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Range2F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_range2f_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_range2f_proto_goTypes,
		DependencyIndexes: file_range2f_proto_depIdxs,
		MessageInfos:      file_range2f_proto_msgTypes,
	}.Build()
	File_range2f_proto = out.File
	file_range2f_proto_rawDesc = nil
	file_range2f_proto_goTypes = nil
	file_range2f_proto_depIdxs = nil
}
