// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: time_stamp.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeStamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year     *uint32 `protobuf:"varint,1,req,name=year" json:"year,omitempty"`
	Month    *uint32 `protobuf:"varint,2,req,name=month" json:"month,omitempty"`
	Day      *uint32 `protobuf:"varint,3,req,name=day" json:"day,omitempty"`
	Hour     *uint32 `protobuf:"varint,4,req,name=hour" json:"hour,omitempty"`
	Minute   *uint32 `protobuf:"varint,5,req,name=minute" json:"minute,omitempty"`
	Second   *uint32 `protobuf:"varint,6,req,name=second" json:"second,omitempty"`
	TzOffset *int32  `protobuf:"zigzag32,7,opt,name=tz_offset,json=tzOffset" json:"tz_offset,omitempty"`
}

func (x *TimeStamp) Reset() {
	*x = TimeStamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_time_stamp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStamp) ProtoMessage() {}

func (x *TimeStamp) ProtoReflect() protoreflect.Message {
	mi := &file_time_stamp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStamp.ProtoReflect.Descriptor instead.
func (*TimeStamp) Descriptor() ([]byte, []int) {
	return file_time_stamp_proto_rawDescGZIP(), []int{0}
}

func (x *TimeStamp) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *TimeStamp) GetMonth() uint32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *TimeStamp) GetDay() uint32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

func (x *TimeStamp) GetHour() uint32 {
	if x != nil && x.Hour != nil {
		return *x.Hour
	}
	return 0
}

func (x *TimeStamp) GetMinute() uint32 {
	if x != nil && x.Minute != nil {
		return *x.Minute
	}
	return 0
}

func (x *TimeStamp) GetSecond() uint32 {
	if x != nil && x.Second != nil {
		return *x.Second
	}
	return 0
}

func (x *TimeStamp) GetTzOffset() int32 {
	if x != nil && x.TzOffset != nil {
		return *x.TzOffset
	}
	return 0
}

var File_time_stamp_proto protoreflect.FileDescriptor

var file_time_stamp_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6c, 0x74, 0x70, 0x62, 0x22, 0xa8, 0x01, 0x0a, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x64,
	0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x04, 0x68, 0x6f, 0x75, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x7a, 0x5f, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x11, 0x52, 0x08, 0x74, 0x7a, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x74, 0x70, 0x62, 0x3b, 0x6c, 0x74,
	0x70, 0x62,
}

var (
	file_time_stamp_proto_rawDescOnce sync.Once
	file_time_stamp_proto_rawDescData = file_time_stamp_proto_rawDesc
)

func file_time_stamp_proto_rawDescGZIP() []byte {
	file_time_stamp_proto_rawDescOnce.Do(func() {
		file_time_stamp_proto_rawDescData = protoimpl.X.CompressGZIP(file_time_stamp_proto_rawDescData)
	})
	return file_time_stamp_proto_rawDescData
}

var file_time_stamp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_time_stamp_proto_goTypes = []any{
	(*TimeStamp)(nil), // 0: ltpb.TimeStamp
}
var file_time_stamp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_stamp_proto_init() }
func file_time_stamp_proto_init() {
	if File_time_stamp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_time_stamp_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TimeStamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_time_stamp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_time_stamp_proto_goTypes,
		DependencyIndexes: file_time_stamp_proto_depIdxs,
		MessageInfos:      file_time_stamp_proto_msgTypes,
	}.Build()
	File_time_stamp_proto = out.File
	file_time_stamp_proto_rawDesc = nil
	file_time_stamp_proto_goTypes = nil
	file_time_stamp_proto_depIdxs = nil
}
