// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc1
// source: vignetting_characterization.proto

package ltpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VignettingCharacterization struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crosstalk          *VignettingCharacterization_CrosstalkModel          `protobuf:"bytes,1,req,name=crosstalk" json:"crosstalk,omitempty"`
	Vignetting         []*VignettingCharacterization_MirrorVignettingModel `protobuf:"bytes,2,rep,name=vignetting" json:"vignetting,omitempty"`
	RelativeBrightness *float32                                            `protobuf:"fixed32,3,opt,name=relative_brightness,json=relativeBrightness" json:"relative_brightness,omitempty"`
	LensHallCode       *int32                                              `protobuf:"varint,4,opt,name=lens_hall_code,json=lensHallCode" json:"lens_hall_code,omitempty"`
}

func (x *VignettingCharacterization) Reset() {
	*x = VignettingCharacterization{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vignetting_characterization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VignettingCharacterization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VignettingCharacterization) ProtoMessage() {}

func (x *VignettingCharacterization) ProtoReflect() protoreflect.Message {
	mi := &file_vignetting_characterization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VignettingCharacterization.ProtoReflect.Descriptor instead.
func (*VignettingCharacterization) Descriptor() ([]byte, []int) {
	return file_vignetting_characterization_proto_rawDescGZIP(), []int{0}
}

func (x *VignettingCharacterization) GetCrosstalk() *VignettingCharacterization_CrosstalkModel {
	if x != nil {
		return x.Crosstalk
	}
	return nil
}

func (x *VignettingCharacterization) GetVignetting() []*VignettingCharacterization_MirrorVignettingModel {
	if x != nil {
		return x.Vignetting
	}
	return nil
}

func (x *VignettingCharacterization) GetRelativeBrightness() float32 {
	if x != nil && x.RelativeBrightness != nil {
		return *x.RelativeBrightness
	}
	return 0
}

func (x *VignettingCharacterization) GetLensHallCode() int32 {
	if x != nil && x.LensHallCode != nil {
		return *x.LensHallCode
	}
	return 0
}

type VignettingCharacterization_CrosstalkModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width      *uint32       `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height     *uint32       `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Data       []*Matrix4X4F `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	DataPacked []float32     `protobuf:"fixed32,4,rep,packed,name=data_packed,json=dataPacked" json:"data_packed,omitempty"`
}

func (x *VignettingCharacterization_CrosstalkModel) Reset() {
	*x = VignettingCharacterization_CrosstalkModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vignetting_characterization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VignettingCharacterization_CrosstalkModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VignettingCharacterization_CrosstalkModel) ProtoMessage() {}

func (x *VignettingCharacterization_CrosstalkModel) ProtoReflect() protoreflect.Message {
	mi := &file_vignetting_characterization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VignettingCharacterization_CrosstalkModel.ProtoReflect.Descriptor instead.
func (*VignettingCharacterization_CrosstalkModel) Descriptor() ([]byte, []int) {
	return file_vignetting_characterization_proto_rawDescGZIP(), []int{0, 0}
}

func (x *VignettingCharacterization_CrosstalkModel) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *VignettingCharacterization_CrosstalkModel) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *VignettingCharacterization_CrosstalkModel) GetData() []*Matrix4X4F {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VignettingCharacterization_CrosstalkModel) GetDataPacked() []float32 {
	if x != nil {
		return x.DataPacked
	}
	return nil
}

type VignettingCharacterization_MirrorVignettingModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HallCode   *int32                                      `protobuf:"varint,1,req,name=hall_code,json=hallCode" json:"hall_code,omitempty"`
	Vignetting *VignettingCharacterization_VignettingModel `protobuf:"bytes,2,req,name=vignetting" json:"vignetting,omitempty"`
}

func (x *VignettingCharacterization_MirrorVignettingModel) Reset() {
	*x = VignettingCharacterization_MirrorVignettingModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vignetting_characterization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VignettingCharacterization_MirrorVignettingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VignettingCharacterization_MirrorVignettingModel) ProtoMessage() {}

func (x *VignettingCharacterization_MirrorVignettingModel) ProtoReflect() protoreflect.Message {
	mi := &file_vignetting_characterization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VignettingCharacterization_MirrorVignettingModel.ProtoReflect.Descriptor instead.
func (*VignettingCharacterization_MirrorVignettingModel) Descriptor() ([]byte, []int) {
	return file_vignetting_characterization_proto_rawDescGZIP(), []int{0, 1}
}

func (x *VignettingCharacterization_MirrorVignettingModel) GetHallCode() int32 {
	if x != nil && x.HallCode != nil {
		return *x.HallCode
	}
	return 0
}

func (x *VignettingCharacterization_MirrorVignettingModel) GetVignetting() *VignettingCharacterization_VignettingModel {
	if x != nil {
		return x.Vignetting
	}
	return nil
}

type VignettingCharacterization_VignettingModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  *uint32   `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height *uint32   `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Data   []float32 `protobuf:"fixed32,3,rep,packed,name=data" json:"data,omitempty"`
}

func (x *VignettingCharacterization_VignettingModel) Reset() {
	*x = VignettingCharacterization_VignettingModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vignetting_characterization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VignettingCharacterization_VignettingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VignettingCharacterization_VignettingModel) ProtoMessage() {}

func (x *VignettingCharacterization_VignettingModel) ProtoReflect() protoreflect.Message {
	mi := &file_vignetting_characterization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VignettingCharacterization_VignettingModel.ProtoReflect.Descriptor instead.
func (*VignettingCharacterization_VignettingModel) Descriptor() ([]byte, []int) {
	return file_vignetting_characterization_proto_rawDescGZIP(), []int{0, 2}
}

func (x *VignettingCharacterization_VignettingModel) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *VignettingCharacterization_VignettingModel) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *VignettingCharacterization_VignettingModel) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_vignetting_characterization_proto protoreflect.FileDescriptor

var file_vignetting_characterization_proto_rawDesc = []byte{
	0x0a, 0x21, 0x76, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x74, 0x70, 0x62, 0x1a, 0x10, 0x6d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x34, 0x78, 0x34, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x05, 0x0a, 0x1a,
	0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x09, 0x63, 0x72,
	0x6f, 0x73, 0x73, 0x74, 0x61, 0x6c, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x6c, 0x74, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x72, 0x6f, 0x73, 0x73, 0x74, 0x61, 0x6c, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09,
	0x63, 0x72, 0x6f, 0x73, 0x73, 0x74, 0x61, 0x6c, 0x6b, 0x12, 0x56, 0x0a, 0x0a, 0x76, 0x69, 0x67,
	0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e,
	0x6c, 0x74, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0a, 0x76, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x12, 0x2f, 0x0a, 0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x65, 0x6e, 0x73, 0x5f, 0x68, 0x61, 0x6c, 0x6c, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6c, 0x65, 0x6e, 0x73,
	0x48, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x89, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x6f,
	0x73, 0x73, 0x74, 0x61, 0x6c, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x74, 0x70, 0x62, 0x2e, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x34, 0x78, 0x34, 0x46, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x64, 0x1a, 0x86, 0x01, 0x0a, 0x15, 0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x56,
	0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1b,
	0x0a, 0x09, 0x68, 0x61, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x08, 0x68, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x50, 0x0a, 0x0a, 0x76,
	0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x6c, 0x74, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x0a, 0x76, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x57, 0x0a,
	0x0f, 0x56, 0x69, 0x67, 0x6e, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x02, 0x42, 0x02, 0x10, 0x01,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x74, 0x70, 0x62,
	0x3b, 0x6c, 0x74, 0x70, 0x62,
}

var (
	file_vignetting_characterization_proto_rawDescOnce sync.Once
	file_vignetting_characterization_proto_rawDescData = file_vignetting_characterization_proto_rawDesc
)

func file_vignetting_characterization_proto_rawDescGZIP() []byte {
	file_vignetting_characterization_proto_rawDescOnce.Do(func() {
		file_vignetting_characterization_proto_rawDescData = protoimpl.X.CompressGZIP(file_vignetting_characterization_proto_rawDescData)
	})
	return file_vignetting_characterization_proto_rawDescData
}

var file_vignetting_characterization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vignetting_characterization_proto_goTypes = []any{
	(*VignettingCharacterization)(nil),                       // 0: ltpb.VignettingCharacterization
	(*VignettingCharacterization_CrosstalkModel)(nil),        // 1: ltpb.VignettingCharacterization.CrosstalkModel
	(*VignettingCharacterization_MirrorVignettingModel)(nil), // 2: ltpb.VignettingCharacterization.MirrorVignettingModel
	(*VignettingCharacterization_VignettingModel)(nil),       // 3: ltpb.VignettingCharacterization.VignettingModel
	(*Matrix4X4F)(nil), // 4: ltpb.Matrix4x4F
}
var file_vignetting_characterization_proto_depIdxs = []int32{
	1, // 0: ltpb.VignettingCharacterization.crosstalk:type_name -> ltpb.VignettingCharacterization.CrosstalkModel
	2, // 1: ltpb.VignettingCharacterization.vignetting:type_name -> ltpb.VignettingCharacterization.MirrorVignettingModel
	4, // 2: ltpb.VignettingCharacterization.CrosstalkModel.data:type_name -> ltpb.Matrix4x4F
	3, // 3: ltpb.VignettingCharacterization.MirrorVignettingModel.vignetting:type_name -> ltpb.VignettingCharacterization.VignettingModel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vignetting_characterization_proto_init() }
func file_vignetting_characterization_proto_init() {
	if File_vignetting_characterization_proto != nil {
		return
	}
	file_matrix4x4f_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vignetting_characterization_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VignettingCharacterization); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vignetting_characterization_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VignettingCharacterization_CrosstalkModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vignetting_characterization_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VignettingCharacterization_MirrorVignettingModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vignetting_characterization_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*VignettingCharacterization_VignettingModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vignetting_characterization_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vignetting_characterization_proto_goTypes,
		DependencyIndexes: file_vignetting_characterization_proto_depIdxs,
		MessageInfos:      file_vignetting_characterization_proto_msgTypes,
	}.Build()
	File_vignetting_characterization_proto = out.File
	file_vignetting_characterization_proto_rawDesc = nil
	file_vignetting_characterization_proto_goTypes = nil
	file_vignetting_characterization_proto_depIdxs = nil
}
